# Generated by Django 4.2.6 on 2023-10-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
