# Generated by Django 4.2.6 on 2023-10-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
    ]
